<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" name="growbot">
	<xacro:include filename="$(find growbot_sim)/urdf/macros.xacro" />
	<xacro:include filename="$(find growbot_sim)/urdf/components/carousel.xacro" />

	<xacro:property name="chassis_support_width" value="0.2" />
	<xacro:property name="chassis_support_length" value="0.1" />
	<xacro:property name="chassis_support_height" value="2.5" />
	<xacro:property name="chassis_support_mass" value="5" />
	<xacro:property name="chassis_mass" value="5" />

	<xacro:property name="carousel_offset" value="1.3" />


	<link name="chassis_support_left_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_support_width} ${chassis_support_length} ${chassis_support_height}" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_support_width} ${chassis_support_length} ${chassis_support_height}" />
			</geometry>
		</collision>
		<inertial>
			<mass value="${chassis_support_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<xacro:box_inertia m="${chassis_support_mass}" x="${chassis_support_width}" y="${chassis_support_length}" z="${chassis_support_height}" />
		</inertial>
	</link>

	<link name="chassis_support_right_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_support_width} ${chassis_support_length} ${chassis_support_height}" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${chassis_support_width} ${chassis_support_length} ${chassis_support_height}" />
			</geometry>
		</collision>
		<inertial>
			<mass value="${chassis_support_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<xacro:box_inertia m="${chassis_support_mass}" x="${chassis_support_width}" y="${chassis_support_length}" z="${chassis_support_height}" />
		</inertial>
	</link>


	<joint name="chassis_support_left_join" type="fixed">
		<origin xyz="0 ${carousel_width/2+carousel_wheel_width} ${chassis_support_height/2}" />
		<parent link="base_link"/>
		<child link="chassis_support_left_link" />
		<axis xyz="0 1 0"/>
	</joint>

	<joint name="chassis_support_right_join" type="fixed">
		<origin xyz="0 ${-carousel_width/2-carousel_wheel_width} ${chassis_support_height/2}" />
		<parent link="base_link"/>
		<child link="chassis_support_right_link" />
		<axis xyz="0 1 0"/>
	</joint>

	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${2*carousel_wheel_radius} ${carousel_width+chassis_support_width*2} 0.1" />
			</geometry>
		</visual>
		<collision>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<box size="${2*carousel_wheel_radius} ${carousel_width+chassis_support_width*2} 0.1" />
			</geometry>
		</collision>
		<inertial>
			<mass value="${chassis_mass}"/>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<xacro:box_inertia m="${chassis_mass}" x="${2*carousel_wheel_radius}" y="${carousel_width+chassis_support_width*2}" z="0.1" />
		</inertial>
	</link>

	<joint name="carousel_center_join" type="continuous">
		<origin xyz="0 ${-carousel_width/2-chassis_support_length*20/13} 0" />
		<parent link="chassis_support_left_link"/>
		<child link="carousel_center_link" />
		<axis xyz="0 1 0"/>
	</joint>

	<transmission name="carousel_center_trans">
		<type>hardware_interface</type>
		<joint name="carousel_center_join">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
		</joint>
		<actuator name="carousel_center_motor">
			<hardwareInterface>EffortJointInterface</hardwareInterface>
			<mechanicalReduction>1</mechanicalReduction>
		</actuator>
	</transmission>

	<gazebo>
		<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>/growbot</robotNamespace>
		</plugin>
	</gazebo>
</robot>
