<?xml version="1.0" ?>

<robot name="slambot" 
    xmlns:xacro="https://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find growbot_sim)/urdf/components/box_link.xacro" />


    <xacro:property name="carousel_wheel_mass" value="2" />
    <xacro:property name="carousel_wheel_radius" value="1" />
    <xacro:property name="carousel_wheel_width" value="0.15" />
    <xacro:property name="carousel_width" value="2" />
    <xacro:property name="carousel_box_height" value="0.3" />
    <xacro:property name="carousel_box_length" value="0.5" />
    <xacro:property name="carousel_box_weight" value="5" />
    <xacro:property name="carousel_center_radius" value="0.05" />
    <xacro:property name="carousel_center_weight" value="2" />

    <link name="carousel_center_link">
        <visual>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
            <geometry>
                <cylinder length="${carousel_width}" radius="${carousel_center_radius}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
            <geometry>
                <cylinder length="${carousel_width}" radius="${carousel_center_radius}" />
            </geometry>
            <material name="red"/>
        </collision>
        <inertial>
            <mass value="${carousel_center_weight}" />
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <cylinder_inertia m="${carousel_center_weight}" r="${carousel_center_radius}" h="${carousel_wheel_width}" />
        </inertial>
    </link>

    <joint name="carousel_left_wheel_join" type="fixed">
		<origin xyz="0 ${carousel_width/2} 0" />
		<parent link="carousel_center_link"/>
		<child link="carousel_wheel_left_link" />
		<axis xyz="0 1 0"/>
	</joint>

	<joint name="carousel_right_wheel_join" type="fixed">
		<origin xyz="0 ${-carousel_width/2} 0" />
		<parent link="carousel_center_link"/>
		<child link="carousel_wheel_right_link" />
		<axis xyz="0 1 0"/>
	</joint>


    <link name="carousel_wheel_right_link">
        <inertial>
            <mass value="${carousel_wheel_mass}" />
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <cylinder_inertia m="${carousel_wheel_mass}" r="${carousel_wheel_radius}" h="${carousel_wheel_width}" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder length="${carousel_wheel_width}" radius="${carousel_wheel_radius}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <geometry>
                <cylinder length="${carousel_wheel_width}" radius="${carousel_wheel_radius}" />
            </geometry>
            <material name="red"/>
        </collision>
    </link>

    <link name="carousel_wheel_left_link">
        <visual>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
            <geometry>
                <cylinder length="${carousel_wheel_width}" radius="${carousel_wheel_radius}" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 0" />
            <geometry>
                <cylinder length="${carousel_wheel_width}" radius="${carousel_wheel_radius}" />
            </geometry>
            <material name="red"/>
        </collision>
        <inertial>
            <mass value="${carousel_wheel_mass}" />
            <origin xyz="0 0 0" rpy="${pi/2} 0 0" />
            <cylinder_inertia m="${carousel_wheel_mass}" r="${carousel_wheel_radius}" h="${carousel_wheel_width}" />
        </inertial>
    </link>

    <joint name="carousel_box_0_link_join" type="continuous">
        <origin xyz="${carousel_wheel_radius/2+carousel_box_length/2} ${carousel_width/2} 0" />
        <parent link="carousel_wheel_right_link"/>
        <child link="carousel_box_0_link" />
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="carousel_box_1_link_join" type="continuous">
        <origin xyz="0 ${carousel_width/2} ${carousel_wheel_radius/2+carousel_box_length/2}" />
        <parent link="carousel_wheel_right_link"/>
        <child link="carousel_box_1_link" />
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="carousel_box_2_link_join" type="continuous">
        <origin xyz="${-carousel_wheel_radius/2-carousel_box_length/2} ${carousel_width/2} 0" />
        <parent link="carousel_wheel_right_link"/>
        <child link="carousel_box_2_link" />
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="carousel_box_3_link_join" type="continuous">
        <origin xyz="0 ${carousel_width/2} ${-carousel_wheel_radius/2-carousel_box_length/2}" />
        <parent link="carousel_wheel_right_link"/>
        <child link="carousel_box_3_link" />
        <axis xyz="0 1 0"/>
    </joint>

    <box_link name="carousel_box_0_link" m="${carousel_box_weight}" x="${carousel_box_length}" y="${carousel_width}" z="${carousel_box_height}" />

    <box_link name="carousel_box_1_link" m="${carousel_box_weight}" x="${carousel_box_length}" y="${carousel_width}" z="${carousel_box_height}" />

    <box_link name="carousel_box_2_link" m="${carousel_box_weight}" x="${carousel_box_length}" y="${carousel_width}" z="${carousel_box_height}" />

    <box_link name="carousel_box_3_link" m="${carousel_box_weight}" x="${carousel_box_length}" y="${carousel_width}" z="${carousel_box_height}" />

</robot>